//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int id_bitacora { get; set; }
        public string transaccion { get; set; }
        public string fecha { get; set; }
    }
}
