//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provedor()
        {
            this.ProdProvedor = new HashSet<ProdProvedor>();
        }
    
        public int id_provedor { get; set; }
        public string nombre_provedor { get; set; }
        public string direccion_provedor { get; set; }
        public string correo_provedor { get; set; }
        public string tipo_provedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdProvedor> ProdProvedor { get; set; }
    }
}
