//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.ENTITIES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDContext : DbContext
    {
        public BDContext()
            : base("name=BDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Privilegios> Privilegios { get; set; }
        public virtual DbSet<ProdProvedor> ProdProvedor { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Provedor> Provedor { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<so_iniciar_Sesion_Result> so_iniciar_Sesion(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<so_iniciar_Sesion_Result>("so_iniciar_Sesion", usuarioParameter);
        }
    
        public virtual ObjectResult<Producto> sp_mostrar_Productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Producto>("sp_mostrar_Productos");
        }
    
        public virtual ObjectResult<Producto> sp_mostrar_Productos(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Producto>("sp_mostrar_Productos", mergeOption);
        }
    
        public virtual ObjectResult<Producto> sp_mostrar_Productos1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Producto>("sp_mostrar_Productos1");
        }
    
        public virtual ObjectResult<Producto> sp_mostrar_Productos1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Producto>("sp_mostrar_Productos1", mergeOption);
        }
    
        public virtual ObjectResult<Usuario> so_iniciar_Sesion1(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("so_iniciar_Sesion1", usuarioParameter);
        }
    
        public virtual ObjectResult<Usuario> so_iniciar_Sesion1(string usuario, MergeOption mergeOption)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("so_iniciar_Sesion1", mergeOption, usuarioParameter);
        }
    }
}
